SET SERVEROUTPUT ON;
-- Création du rôle personnalisé ROLE_LAB_RESEARCH
BEGIN
  EXECUTE IMMEDIATE 'CREATE ROLE ROLE_LAB_RESEARCH';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1920 THEN -- Le rôle existe déjà
      DBMS_OUTPUT.PUT_LINE('Erreur ROLE_LAB_RESEARCH : ' || SQLERRM);
      RAISE;
    END IF;
END;
/

-- Création de l'utilisateur ADMIN_LAB
BEGIN
  EXECUTE IMMEDIATE '
    CREATE USER ADMIN_LAB IDENTIFIED BY admin_lab_pwd
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -01920 THEN -- Utilisateur existe déjà
      DBMS_OUTPUT.PUT_LINE('Erreur ADMIN_LAB : ' || SQLERRM);
      RAISE;
    END IF;
END;
/

-- Création de l'utilisateur GEST_LAB
BEGIN
  EXECUTE IMMEDIATE '
    CREATE USER GEST_LAB IDENTIFIED BY gest_lab_pwd
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -01920 THEN
      DBMS_OUTPUT.PUT_LINE('Erreur GEST_LAB : ' || SQLERRM);
      RAISE;
    END IF;
END;
/

-- Création de l'utilisateur LECT_LAB
BEGIN
  EXECUTE IMMEDIATE '
    CREATE USER LECT_LAB IDENTIFIED BY lect_lab_pwd
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
  ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -01920 THEN
      DBMS_OUTPUT.PUT_LINE('Erreur LECT_LAB : ' || SQLERRM);
      RAISE;
    END IF;
END;
/

-- Attribution des rôles système
BEGIN
  EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE, DBA TO ADMIN_LAB';
  EXECUTE IMMEDIATE 'GRANT CONNECT TO GEST_LAB';
  EXECUTE IMMEDIATE 'GRANT CONNECT TO LECT_LAB';
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erreur lors de l''attribution des rôles système : ' || SQLERRM);
    RAISE;
END;
/

-- Attribution du rôle personnalisé
BEGIN
  EXECUTE IMMEDIATE 'GRANT ROLE_LAB_RESEARCH TO ADMIN_LAB';
  EXECUTE IMMEDIATE 'GRANT ROLE_LAB_RESEARCH TO GEST_LAB';
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erreur lors de l''attribution du rôle personnalisé : ' || SQLERRM);
    RAISE;
END;
/